// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI2.Models;

#nullable disable

namespace ProductAPI2.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20240802101245_InıtialCreate")]
    partial class InıtialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("ProductAPI2.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsActive = false,
                            Price = 30000m,
                            ProductName = "iPhone 11"
                        },
                        new
                        {
                            ProductId = 2,
                            IsActive = true,
                            Price = 40000m,
                            ProductName = "iPhone 12"
                        },
                        new
                        {
                            ProductId = 3,
                            IsActive = true,
                            Price = 50000m,
                            ProductName = "iPhone 13"
                        },
                        new
                        {
                            ProductId = 4,
                            IsActive = true,
                            Price = 60000m,
                            ProductName = "iPhone 14"
                        },
                        new
                        {
                            ProductId = 5,
                            IsActive = true,
                            Price = 70000m,
                            ProductName = "iPhone 15"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
